import '@/styles/globals.scss';
import { PlansProvider } from '@/contexts/PlansContext';
import Nav from '@/components/layouts/Nav';

export const metadata = {
  title: 'Track plan',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <PlansProvider>
          <Nav />
          <div className='container'>
            {children}
          </div>
        </PlansProvider>
        <div id='popupPortal'></div>
      </body>
    </html>
  )
}
