import '@/styles/globals.scss';
import { PlansProvider } from '@/contexts/PlansContext';
import Nav from '@/components/layouts/Nav';
import Footer from '@/components/layouts/Footer';

export const metadata = {
  title: 'Track plan',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <PlansProvider>
          <div style={{display: "flex", flexDirection: "column", height: "100vh"}}>
            <Nav />
            <div className='container'>
              {children}
            </div>
            <Footer/>
          </div>
        </PlansProvider>
        <div id='popupPortal'></div>
      </body>
    </html>
  )
}
