import '../styles/globals.css';
import { PlansProvider } from '@/contexts/PlansContext';

export const metadata = {
  title: 'Track plan',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <PlansProvider>
          {children}
        </PlansProvider>
        <div id='popupPortal'></div>
      </body>
    </html>
  )
}
